---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servers.mindustry.operator
spec:
  group: mindustry.operator
  names:
    plural: servers
    singular: server
    kind: Server
  scope: Namespaced
  versions:
  - name: dev
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              version:
                type: string
