---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: mindustry-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mindustry-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: mindustry-operator
---
apiVersion: v1
kind: Pod
metadata:
  namespace: kube-system
  name: mindustry-operator
spec:
  serviceAccount: mindustry-operator
  initContainers:
  - name: installer
    image: python:latest
    command:
    - sh
    - -c
    - |
      python -m venv /venv
      . /venv/bin/activate
      pip install https://github.com/majkrzak/mindustry-operator/archive/master.tar.gz
    volumeMounts:
    - mountPath: /venv
      name: venv
  containers:
  - name: operator
    image: python:slim
    command:
    - sh
    - -c
    - |
      . /venv/bin/activate
      kopf run --all-namespaces -m mindustry_operator
    volumeMounts:
    - mountPath: /venv
      name: venv
  volumes:
  - name: venv
    emptyDir: { }
